### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by davelab6** [qrpike/Web-Font-Load#10]
Please apply a libre license (Apache?) to this repo :)

**Comment by davelab6** [comment]
Ping :)

**Comment by adeluccar** [comment]
+1

I'm interested in either contributing or forking (if no more activity is in the horizon for the current repo). 

Please add a LICENSE. (MIT?)

**Comment by qrpike** [comment]
@adeluccar MIT license

**Comment by adeluccar** [comment]
@qrpike Oh. I didn't notice you pushed your own commit with the license information. You should probably close the issue. ;-)
