### ISSUE TITLE
rm: cannot remove '*.json': No such file or directory

### ISSUE THREAD

**Issue by orschiro** [qrpike/Web-Font-Load#20]
Thanks for this handy script!

I tried it on Ubuntu 17.10 Alpha 2. 

Is this rm error concerning?

```
./google-fonts-22665ba/.gitmodules
rm: cannot remove '*.json': No such file or directory
Fonts installed, cleaning up files..
Updating font cache...
```

**Comment by qrpike** [comment]
No, it just means you have some left over .json files (meta data). A couple MB. Nothing to worry about.

**Comment by orschiro** [comment]
Alright, thanks! :-)
